config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get 'log_in' => 'sessions#new', as: 'new_login'

  post 'log_in'=> 'sessions#create', as: 'login'

  delete 'logout' => 'sessions#destroy', as: 'logout'

  get 'likes/:user_id/:secrets_id' => 'likes#create', as: 'like'

  delete 'likes/:user_id/:secrets_id' => 'likes#destroy', as: 'unlike'

  resources :users

  resources :secrets

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user, required: true
  belongs_to :secret, required: true
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user, required: true
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_save :downcase
  has_many :secrets, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :name, :email, presence: true

  private
    def downcase
      self.name.downcase!
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session.key? 'user_id'
  end

  def require_login
    redirect_to new_login_path unless session.key? 'user_id'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def destroy
    error = []
    @likes= Like.find_by(user_id:params[:user_id],secret_id:params[:secrets_id])
    if @likes != nil
      @like ||= Like.find_by(user_id:params[:user_id], secret_id:params[:secrets_id]).destroy
      return redirect_to secrets_path
    end
    error << "Can like a secret once"
    return redirect_to secrets_path, alert: error
  end
  def create
    error = []
    @likes= Like.find_by(user_id:params[:user_id],secret_id:params[:secrets_id])
    if @likes == nil
      @like ||= Like.create(user_id:params[:user_id], secret_id:params[:secrets_id])
      return redirect_to secrets_path
    end
    error << "Can like a secret once"
    return redirect_to secrets_path, alert: error
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets ||= Secret.eager_load(:user, :likes).all
    render layout:"login_reg"
  end
  def create
		@secret ||= Secret.create(content:params[:content],user_id:session[:user_id])
		if @secret.valid?
			return redirect_to user_path(session[:user_id])
		end

		flash[:alert] = @secret.errors.full_messages
		# p @secret.errors.full_messages
		return redirect_to user_path(session[:user_id])
	end

	def destroy
		@this_secret = Secret.find_by(id: params[:id])
		if session[:user_id] == @this_secret.user.id
			@this_secret.destroy
			return redirect_to user_path(session[:user_id])
		else
			flash[:alert] = ["That is not your secret to destroy."]
			return redirect_to secrets_path
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    render layout:"login_reg"
  end

  def create
    errors = []
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        session[:user_id]= @user.id

        return redirect_to secrets_path
      else
        errors << 'Invalid password/email.'
      end
    else
      errors << 'No corrispinding account.'
    end
    redirect_to :back, alert: errors
  end

  def destroy
    session.delete :user_id if session.key? 'user_id'
    redirect_to new_login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    render layout:"login_reg"
  end
  def create
    if new_user.valid?
      session[:user_id]=new_user.id
      return redirect_to secrets_path
    end
    redirect_to :back, alert: new_user.errors.full_messages
  end
  def show
    if params[:id] == current_user.id
      @my_secrets = Secret.eager_load(:user).where(user_id:session[:user_id])
      p@my_secrets
      user
      render layout:"login_reg"
    end
    return redirect_to secrets_path
  end
  def edit
    if params[:id] == current_user.id
      user
      render layout:"login_reg"
    end
    return redirect_to secrets_path
  end
  def update
    if edit_user.valid?
      return redirect_to secrets_path
    end
    redirect_to :back, alert: edit_user.errors.full_messages
  end
  private
    helper_method def user
      @user ||= User.find(params[:id])
    end
    helper_method def new_user
      @new_user ||= User.create(user_params)
    end
    helper_method def edit_user
      @new_user ||= User.update(session[:user_id],update_params)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoSecrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/login_reg.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js" integrity="sha384-lZmvU/TzxoIQIOD9yQDEpvxp6wEU32Fy0ckUgOH4EIlMOCdR823rg4+3gWRwnX1M" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Dojo Secrets</span>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <%= yield :top_column%>
        </div>
        <div class="col-md-8">
          <%= yield :left_column%>
        </div>
        <div class="col-md-2">
          <%= yield :right_column%>
        </div>
      </div>
    </div>
  <%= yield %>

  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/partials/_errors.html.erb
<% if flash[:alert] %>
  <% flash[:alert].each do |error| %>
    <div class="alert alert-danger" role="alert">
      <p ><%= error %></p>
    </div>
  <% end %>
<% end %>

app/views/secrets/index.html.erb
<% content_for  :left_column do %>
<nav>
  <h1>Hello secrets</h1>
  <a class="btn btn-primary btn-lg"href="<%= user_path(session[:user_id]) %>">Shear a Secret</a>
</nav>
<%= render 'partials/errors' %>
<div class="container center_div">
  <% @secrets.each do |secret| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <p><%= secret.content%></p>
        <button type="button" class="btn btn-primary">
          likes <span class="badge badge-light"><%= secret.likes.count %></span>
          <span class="sr-only">unread messages</span>
        </button>
        <% if secret.user.id == session[:user_id] %>
          <a class="btn btn-outline-danger"href="<%= secret_path(secret.id) %>" data-method="delete">Delete</a>
        <% end %>
        <% unless secret.users.include? current_user %>
            <a class="btn btn-outline-info" href="<%= like_path(session[:user_id],secret.id) %>" >Like</a>
        <% else %>
          <a class="btn btn-outline-danger" href="<%= like_path(session[:user_id],secret.id) %>" data-method="delete">Unlike</a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="">
  <a class="btn btn-danger btn-lg btn-block" href="<%= logout_path %>" data-method="delete">Logout</a>
  <a class="btn btn-secondary btn-lg btn-block"href="/users/<%= session[:user_id] %>/edit">Edit My info</a>
</div>

<% end %>

app/views/secrets/new.html.erb
<% content_for  :left_column do %>
<h1>Hello secrets</h1>

<a href="<%= logout_path %>" data-method="delete">Logout</a>
<a href="/users/<%= @user_id %>/edit">Edit My info</a>
<% end %>

app/views/users/edit.html.erb
<% content_for  :left_column do %>
  <h1>Edit</h1>

  <%= render 'partials/errors' %>

  	<form action="<%= user_path %>" method="post" >
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="form-group">
        <label>Name: </label>
        <input class="form-control" id="exampleFormControlInput1" type="text" name="user[name]" value="<%= @user.name%>">
      </div>
      <div class="form-group">
        <label>Email: </label>
        <input class="form-control" id="exampleFormControlInput1" type="text" name="user[email]" value="<%= @user.email%>">
      </div>
  		<button class="btn btn-primary" type="submit">Edit</button>
  	</form>
<% end %>

app/views/users/new.html.erb
<% content_for  :left_column do %>
  <ul class="nav nav-tabs">
    <h1 class="nav-item"><a class="nav-link active" href="/">Register</a></h1>
    <h1 class="nav-item"><a class="nav-link" href="<%= new_login_path %>">Log_in</a></h1>
  </ul>


  <%= render 'partials/errors' %>

  	<form action="/users" method="post" >
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="form-group">
  		  <label>Name: </label>
        <input class="form-control" id="exampleFormControlInput1" type="text" name="user[name]" placeholder="name">
      </div>
      <div class="form-group">
        <label>Email: </label>
        <input class="form-control" id="exampleFormControlInput1" type="text" name="user[email]" placeholder="email">
      </div>
      <div class="form-group">
        <label>Password: </label>
        <input class="form-control" id="exampleFormControlInput1" type="password" name="user[password]" placeholder="password">
      </div>
      <div class="form-group">
        <label>PW confirmation: </label>
        <input class="form-control" id="exampleFormControlInput1" type="password" name="user[password_confirmation]" placeholder="password confirmation">
      </div>
  		<button class="btn btn-primary" type="submit">Rgister</button>
  	</form>
<% end %>

app/views/users/show.html.erb
<% content_for  :left_column do %>
<div class="">
  <a href="<%= logout_path %>" data-method="delete">Logout</a>
  <a href="<%= secrets_path %>" >Secrets Home</a>
  <a href="/users/<%= session[:user_id] %>/edit">Edit My info</a>
</div>
<h1>Hello <%= @user.name %></h1>
<h2>Share a secret</h2>
<%= render 'partials/errors' %>
<form action="<%= secrets_path %>" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label>Secret: </label>
    <textarea class="form-control" id="exampleFormControlInput1" type="text" name="content" placeholder="Secret" rows="8" cols="80"></textarea>
  </div>
  <button class="btn btn-primary" type="submit">Create!</button>
</form>

<% @my_secrets.each do |secret| %>
  <p><%= secret.content%></p>
  <p><%= secret.likes.count %> likes</p>
  <a href="<%= secret_path(secret.id) %>" data-method="delete"><button> Delete </button></a>
<% end %>


<% end %>